#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameAPISupport.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DemoDVD")]
	public partial class VLVNDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertVietlottVN(VietlottVN instance);
    partial void UpdateVietlottVN(VietlottVN instance);
    partial void DeleteVietlottVN(VietlottVN instance);
    #endregion
		
		public VLVNDataContext() : 
				base(global::GameAPISupport.Properties.Settings.Default.DemoDVDConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public VLVNDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VLVNDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VLVNDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VLVNDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VietlottVN> VietlottVNs
		{
			get
			{
				return this.GetTable<VietlottVN>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CountFrequencyNumber")]
		public ISingleResult<CountFrequencyNumberResult> CountFrequencyNumber([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> myNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), myNumber);
			return ((ISingleResult<CountFrequencyNumberResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VietlottVN")]
	public partial class VietlottVN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _VietLottID;
		
		private int _DrawId;
		
		private System.DateTime _DayPrize;
		
		private string _FullBlockNumber;
		
		private int _NumberOne;
		
		private int _NumberTwo;
		
		private int _NumberThree;
		
		private int _NumberFour;
		
		private int _NumberFive;
		
		private int _NumberSix;
		
		private System.DateTime _ImportDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVietLottIDChanging(int value);
    partial void OnVietLottIDChanged();
    partial void OnDrawIdChanging(int value);
    partial void OnDrawIdChanged();
    partial void OnDayPrizeChanging(System.DateTime value);
    partial void OnDayPrizeChanged();
    partial void OnFullBlockNumberChanging(string value);
    partial void OnFullBlockNumberChanged();
    partial void OnNumberOneChanging(int value);
    partial void OnNumberOneChanged();
    partial void OnNumberTwoChanging(int value);
    partial void OnNumberTwoChanged();
    partial void OnNumberThreeChanging(int value);
    partial void OnNumberThreeChanged();
    partial void OnNumberFourChanging(int value);
    partial void OnNumberFourChanged();
    partial void OnNumberFiveChanging(int value);
    partial void OnNumberFiveChanged();
    partial void OnNumberSixChanging(int value);
    partial void OnNumberSixChanged();
    partial void OnImportDateChanging(System.DateTime value);
    partial void OnImportDateChanged();
    #endregion
		
		public VietlottVN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VietLottID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int VietLottID
		{
			get
			{
				return this._VietLottID;
			}
			set
			{
				if ((this._VietLottID != value))
				{
					this.OnVietLottIDChanging(value);
					this.SendPropertyChanging();
					this._VietLottID = value;
					this.SendPropertyChanged("VietLottID");
					this.OnVietLottIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrawId", DbType="Int NOT NULL")]
		public int DrawId
		{
			get
			{
				return this._DrawId;
			}
			set
			{
				if ((this._DrawId != value))
				{
					this.OnDrawIdChanging(value);
					this.SendPropertyChanging();
					this._DrawId = value;
					this.SendPropertyChanged("DrawId");
					this.OnDrawIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DayPrize", DbType="DateTime NOT NULL")]
		public System.DateTime DayPrize
		{
			get
			{
				return this._DayPrize;
			}
			set
			{
				if ((this._DayPrize != value))
				{
					this.OnDayPrizeChanging(value);
					this.SendPropertyChanging();
					this._DayPrize = value;
					this.SendPropertyChanged("DayPrize");
					this.OnDayPrizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullBlockNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FullBlockNumber
		{
			get
			{
				return this._FullBlockNumber;
			}
			set
			{
				if ((this._FullBlockNumber != value))
				{
					this.OnFullBlockNumberChanging(value);
					this.SendPropertyChanging();
					this._FullBlockNumber = value;
					this.SendPropertyChanged("FullBlockNumber");
					this.OnFullBlockNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOne", DbType="Int NOT NULL")]
		public int NumberOne
		{
			get
			{
				return this._NumberOne;
			}
			set
			{
				if ((this._NumberOne != value))
				{
					this.OnNumberOneChanging(value);
					this.SendPropertyChanging();
					this._NumberOne = value;
					this.SendPropertyChanged("NumberOne");
					this.OnNumberOneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberTwo", DbType="Int NOT NULL")]
		public int NumberTwo
		{
			get
			{
				return this._NumberTwo;
			}
			set
			{
				if ((this._NumberTwo != value))
				{
					this.OnNumberTwoChanging(value);
					this.SendPropertyChanging();
					this._NumberTwo = value;
					this.SendPropertyChanged("NumberTwo");
					this.OnNumberTwoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberThree", DbType="Int NOT NULL")]
		public int NumberThree
		{
			get
			{
				return this._NumberThree;
			}
			set
			{
				if ((this._NumberThree != value))
				{
					this.OnNumberThreeChanging(value);
					this.SendPropertyChanging();
					this._NumberThree = value;
					this.SendPropertyChanged("NumberThree");
					this.OnNumberThreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberFour", DbType="Int NOT NULL")]
		public int NumberFour
		{
			get
			{
				return this._NumberFour;
			}
			set
			{
				if ((this._NumberFour != value))
				{
					this.OnNumberFourChanging(value);
					this.SendPropertyChanging();
					this._NumberFour = value;
					this.SendPropertyChanged("NumberFour");
					this.OnNumberFourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberFive", DbType="Int NOT NULL")]
		public int NumberFive
		{
			get
			{
				return this._NumberFive;
			}
			set
			{
				if ((this._NumberFive != value))
				{
					this.OnNumberFiveChanging(value);
					this.SendPropertyChanging();
					this._NumberFive = value;
					this.SendPropertyChanged("NumberFive");
					this.OnNumberFiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberSix", DbType="Int NOT NULL")]
		public int NumberSix
		{
			get
			{
				return this._NumberSix;
			}
			set
			{
				if ((this._NumberSix != value))
				{
					this.OnNumberSixChanging(value);
					this.SendPropertyChanging();
					this._NumberSix = value;
					this.SendPropertyChanged("NumberSix");
					this.OnNumberSixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImportDate", DbType="DateTime NOT NULL")]
		public System.DateTime ImportDate
		{
			get
			{
				return this._ImportDate;
			}
			set
			{
				if ((this._ImportDate != value))
				{
					this.OnImportDateChanging(value);
					this.SendPropertyChanging();
					this._ImportDate = value;
					this.SendPropertyChanged("ImportDate");
					this.OnImportDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class CountFrequencyNumberResult
	{
		
		private System.Nullable<int> _total;
		
		public CountFrequencyNumberResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Int")]
		public System.Nullable<int> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
